string_ = "KYRGYZSTAN"
print(string_[2])
print(string_[1:])
print(string_[:6])
print(string_[8:])
print(string_[1::2])
print(string_[0::2])
print(string_[::-1])
print(string_[::-1][::2])
print(len(string_))